#!/usr/bin/env python3

"""
A cmd2 console that integrates all impacket-tools into one.

Vision is an metasploit-style console that allows you to set inputs then load impacket modules for AD red teaming.

"""
import cmd2
from cmd2 import (
    Color,
    stylize,
)
from rich.style import Style
import SearchModules
import sys
import os
import subprocess
import argparse
import json
import PrintTable
import FlagUtils
import modules
from Options import Options

cmd2.Cmd.DEFAULT_CATEGORY = "ADAConsole Commands"

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
REPO_ROOT = os.path.dirname(SCRIPT_DIR)

BANNER = """
========================================================================
   Activate Directory Attacker Console (ADAConsole) v0.1.0
========================================================================
Type `help` for commands
"""

# Command categories
MODULE_EXPLORATION = "Explore available modules"
MODULE_USAGE = "Use a specified module"
MODULE_EXECUTION = "Execute a module"

class adaConsole(cmd2.Cmd):
    """Basic app to get started"""

    def __init__(self):
        # Initialise cmd2
        super().__init__(
            auto_suggest=True,
            persistent_history_file="cmd2_history.dat",
        )

        # Stash modules data
        # modules.json is generated by generate_modules.py, which statically scans
        # impacket/examples/*.py for their argparse flags - rerun it after pulling
        # upstream impacket changes to keep the catalog in sync.
        with open("./modules.json", 'r', encoding='utf-8') as file:
            data = json.load(file)

        self.modules = data["modules"]

        self.intro = (
                stylize(
                    BANNER,
                    style=Style(color=Color.GREEN1, bgcolor=Color.GRAY0, bold=True),
                )
        )

        self.hidden_commands += [
            "alias", "edit", "history", "macro", "run_pyscript",
            "run_script", "shell", "shortcuts"
        ]

        # Show this as the prompt when asking for input
        self.prompt = "console> "

        self.selectedModule = None
        self.selectedModuleOptions = None


    moduleListParser = cmd2.Cmd2ArgumentParser(description="List available modules")
    moduleListParser.add_argument(
        "-a", "--all", action="store_true",
        help="Also list modules that don't have a runner implemented yet (can't be 'run')"
    )

    @cmd2.with_category(MODULE_EXPLORATION)
    @cmd2.with_argparser(moduleListParser)
    def do_list(self, args: argparse.Namespace):
        """List available modules. By default only modules that can actually
        be 'run' are shown - pass -a/--all to see the full catalog."""
        shownModules = self.modules if args.all else [m for m in self.modules if m.get("implemented")]
        self.poutput(PrintTable.createTable(shownModules))

    moduleSearchParser = cmd2.Cmd2ArgumentParser(description="Search for modules")
    moduleSearchParser.add_argument("search_terms", help="search terms to search")
    moduleSearchParser.add_argument(
        "-a", "--all", action="store_true",
        help="Also search modules that don't have a runner implemented yet (can't be 'run')"
    )

    # TODO refine arguments, e.g. add function to search just name or just description
    @cmd2.with_category(MODULE_EXPLORATION)
    @cmd2.with_argparser(moduleSearchParser)
    def do_search(self, args: argparse.Namespace):
        """Search modules"""

        searchableModules = self.modules if args.all else [m for m in self.modules if m.get("implemented")]
        resultsTable, numResults = SearchModules.searchModule(searchableModules, args.search_terms)

        numResultsString = "{} Results Found:\n".format(numResults) if numResults else "No Results Found"

        self.poutput(numResultsString)
        self.poutput(PrintTable.createTable(resultsTable))


    moduleUseParser = cmd2.Cmd2ArgumentParser(description="Select a module to use by name or id")
    moduleUseParser.add_argument("module", help="Module name (e.g. secretsdump) or numeric id (e.g. 5)", type=str)

    @cmd2.with_category(MODULE_USAGE)
    @cmd2.with_argparser(moduleUseParser)
    def do_use(self, args: argparse.Namespace):
        """Select a module to use by name or id."""
        targetModule = args.module

        # Get the name or id depending on input - and perform the search logic
        if targetModule.isdigit():
            module = SearchModules.searchModuleId(self.modules, targetModule)
        else:
            module = SearchModules.searchModuleName(self.modules, targetModule)

            if module is None:
                # Fall back to a fuzzy search so partial names still work,
                # but only auto-select when the search is unambiguous.
                searchResults, numResults = SearchModules.searchModule(self.modules, targetModule)

                if numResults == 1:
                    module = searchResults[0]
                elif numResults > 1:
                    self.poutput(f"{numResults} modules matched '{targetModule}', be more specific:")
                    self.poutput(PrintTable.createTable(searchResults))
                    return

        if module is None:
            self.poutput(f"Module not found: {targetModule}")
            return

        self.selectedModule = module
        self.selectedModuleOptions = Options()
        self.prompt = "console ({}) > ".format(module["name"])

        self.poutput("Selected: " + module["name"])

    @cmd2.with_category(MODULE_USAGE)
    def do_options(self, args):
        """Show the required/optional flags for the currently selected module
        and any values already set with 'set'."""
        if self.selectedModule is None:
            self.poutput("No module selected. Use 'use <module>' first.")
            return

        self.poutput(PrintTable.createOptionsTable(self.selectedModule, self.selectedModuleOptions))

    # Not using @cmd2.with_argparser here: most flags in modules.json start
    # with a dash (e.g. "-dc-ip"), and argparse treats any leading-dash token
    # as an option for the *do_set command itself* rather than as a value for
    # our "option" positional, no matter how that positional is declared.
    # Parsing the raw argument string ourselves sidesteps that entirely.
    @cmd2.with_category(MODULE_USAGE)
    def do_set(self, args):
        """Set a value for an option on the currently selected module.

        Usage: set <option> <value>
        Example: set dc-ip 10.0.0.1
        """
        if self.selectedModule is None:
            self.poutput("No module selected. Use 'use <module>' first.")
            return

        parts = str(args).split(None, 1)
        if not parts:
            self.poutput("Usage: set <option> <value>")
            return

        if len(parts) == 1:
            # Convenience for boolean/no-value flags, e.g. "set request"
            # instead of "set request true".
            option, value = parts[0], "true"
        else:
            option, value = parts

        validFlags = self.selectedModule["required flags"] + self.selectedModule["optional flags"]
        validAttrs = {FlagUtils.flag_to_attr(entry["flag"]): entry["flag"] for entry in validFlags}

        attr = FlagUtils.flag_to_attr(option)

        if attr not in validAttrs:
            self.poutput("'{}' is not a valid option for {}".format(option, self.selectedModule["name"]))
            return

        setattr(self.selectedModuleOptions, attr, value)
        self.poutput("{} => {}".format(validAttrs[attr], value))

    @cmd2.with_category(MODULE_EXECUTION)
    def do_run(self, args):
        """Run the currently selected module with the options that have been set."""
        if self.selectedModule is None:
            self.poutput("No module selected. Use 'use <module>' first.")
            return

        if not self.selectedModule.get("implemented"):
            self.poutput(
                "'{}' doesn't have a runner implemented yet. See console/modules/base.py "
                "and console/modules/__init__.py for how to add one.".format(self.selectedModule["name"])
            )
            return

        runner = modules.get_runner(self.selectedModule)

        errors = runner.validate(self.selectedModuleOptions)
        if errors:
            self.poutput("Cannot run - missing/invalid options:")
            for error in errors:
                self.poutput("  - " + error)
            return

        scriptPath = runner.script_path(REPO_ROOT)
        argv = [sys.executable, scriptPath] + runner.build_argv(self.selectedModuleOptions)

        self.poutput("Running: " + " ".join(str(a) for a in argv))
        try:
            subprocess.run(argv)
        except OSError as e:
            self.poutput("Failed to launch module: {}".format(e))


if __name__ == '__main__':
    app = adaConsole()
    sys.exit(app.cmdloop())
